name: lint proto files with `buf`
on: [pull_request]
jobs:
  verify_pr_for_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
      # Run lint only in the `src` sub-directory
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: src
      # Uncomment when the first iteration of the protos are set up
      # Change the repository accordingly
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     input: src
      #     # The 'main' branch of the GitHub repository that defines the module.
      #     against: "https://github.com/Yaydoo/proto.boilerplate.git#branch=main,subdir=src"
